### ISSUE TITLE
Invisibility command

### ISSUE THREAD

**Issue by lewmilburn** [LewMC/Essence#154]

**Comment by dankfmemes** [comment]
Hello, I have previously made contributions to the repository as "shawnjb" but no longer have access to that account. I am considering assisting with the plugin's updates since I am currently studying Java and IT. I thought it would be a good opportunity to apply my knowledge in this area and hope it proves to be beneficial.

**Comment by lewmilburn** [comment]
> Hello, I have previously made contributions to the repository as "shawnjb" but no longer have access to that account. I am considering assisting with the plugin's updates since I am currently studying Java and IT. I thought it would be a good opportunity to apply my knowledge in this area and hope it proves to be beneficial.
> 
> I'll try to solve this one for starters.

Hey, thank you! Feel free to submit as many contributions as you'd like, it's always great to get some help! I'm focused on pushing a huge update for my other plugin [Kryponite](https://github.com/lewmc/kryptonite) at the moment so Essence could do with some TLC getting issues sorted whilst I'm busy over there!

If you need anything feel free to ping me or shoot me a message on Discord (the server link should be in the plugin page), I'm studying at university at the moment so might not get back to you right away but I'll make sure to come by as soon as I can when I get a notification. 😄

**Comment by dankfmemes** [comment]
#163 opened. Hoping that resolves this.
