### ISSUE TITLE
Grief prevention / land claiming

### ISSUE THREAD

**Issue by lewmilburn** [LewMC/Essence#17]

**Comment by byteveil** [comment]
You don't necessarily need to add grief prevention but if you find any good way to integrate Essence with the existing GriefPrevention plugin (if they have a form of support for other plugin developers) then you could find a way to implement a form of group management with the GriefPrevention areas so that whoever claims an area with GriefPrevention can use it to protect their group home or allow group members to build without having to use `/trust` on every single member.

This is just an idea and grief prevention is not necessarily a requirement for the plugin unless you plan to integrate it with the groups feature which would save a lot of people the haasle of trusting all group members.

**Comment by lewmilburn** [comment]
I'll see what I can do with regards to integrating with GriefPrevention :) will be much easier than making my own version haha. Thanks

**Comment by lewmilburn** [comment]
@byteveil can I confirm is it this plugin: https://www.spigotmc.org/resources/griefprevention.1884/

**Comment by byteveil** [comment]
> @byteveil can I confirm is it this plugin: https://www.spigotmc.org/resources/griefprevention.1884/

Yes.
